language: c
before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -qq libapr1-dev liboath-dev unixodbc-dev autotools-dev pkg-config libgnutls28-dev libpam-dev
compiler:
  - gcc
  - clang
script:
  - ./bootstrap
  - ./configure CFLAGS="`apr-1-config --cflags --cppflags --includes` -I/usr/include/liboath"
  - make

